# Generated by Django 5.1.1 on 2024-09-13 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2024, 9, 13, 15, 34, 20, 407150))),
                ('computer_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=64)),
                ('application', models.CharField(max_length=64)),
                ('window_title', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=64)),
                ('screenshot_url', models.CharField(max_length=255)),
            ],
        ),
    ]
